GET http://localhost:8080/cep


###

GET http://localhost:8080/cep/5

###

POST http://localhost:8080/cep
Content-Type:  application/json

{
   "rua":"Wellinto Brother",
   "numero":24,
   "bairro":"Erica city",
   "cidade":"Valinhos",
   "uf":"São Paulo",
   "pessoa": {
      "id": 5,
      "nome": "Maria Casacio",
      "senha": "10587"
   }

}
###

PUT http://localhost:8080/cep
Content-Type:  application/json

{
   "rua":"Assaltos lulas Cadeieiro",
   "numero":24,
   "bairro":"Ladro City",
   "cidade":"Corrupitanos",
   "uf":"Brasilia",
   "pessoa": {
      "id": 5,
      "nome": "Maria Casacio",
      "senha": "10587"
   }

}

###

DELETE http://localhost:8080/cep/5
Content-Type:  application/json
