GET http://localhost:8080/usuarios/cep



###
POST http://localhost:8080/usuarios/cep
Content-Type:  application/json

{
   "rua":"Wellinto Brother",
   "numero":24,
   "bairro":"Erica city",
   "cidade":"Valinhos",
   "uf":"São Paulo",
   "pessoa": {
      "id": 5,
      "nome": "Maria Casacio",
      "senha": "10587"
   }

}
###
PUT http://localhost:8080/usuarios/cep
Content-Type:  application/json

{
   "Rua":"Olympia da Silveira Francoo",
   "Numero":56,
   "Bairro":"Jardim Arizona",
   "Cidade":"Itatiba",
   "Uf":"São Paulo"
}

###
DELETE http://localhost:8080/usuarios/cep
Content-Type:  application/json
