

GET  http://localhost:8080/usuarios

###
POST http://localhost:8080/usuarios
Content-Type:  application/json

{
	"id" : 30,
    "nome":"G braz",
    "senha":"teste"
}

###
PUT  http://localhost:8080/usuarios
Content-Type:  application/json

{
	"id" : 3,
    "nome":"Nenem da Silva Filho",
    "senha":"585487"
}

###
DELETE   http://localhost:8080/usuarios/12
Content-Type:  application/json
