GET  http://localhost:8080/usuarios/

###
POST http://localhost:8080/usuarios
Content-Type:  application/json

{
	"id" : 26,
    "nome":"Gabrielle Martins",
    "senha":"familia é tudo"
}

###
PUT  http://localhost:8080/usuarios
Content-Type:  application/json

{
	"id" : 1,
    "nome":"Nenem da Silva Filho",
    "senha":"585487"
}

###
DELETE   http://localhost:8080/usuarios/1
Content-Type:  application/json
