GET  http://localhost:8080/usuarios/

###
POST http://localhost:8080/usuarios
Content-Type:  application/json
{
	"id" : 1,
    "nome":"Isabelle",
    "senha":"segredo"
}
###
PUT  http://localhost:8080/usuarios
Content-Type:  application/json

{
	"id" : 1,
    "nome":"Nenem da Silva Filho",
    "senha":"MAMA EU"
}

###
DELETE   http://localhost:8080/usuarios/1
Content-Type:  application/json
