POST http://localhost:8080/usuarios
Content-Type:  application/json

{

	"id" : 1,
    "nome":"Isabelle",
    "senha":"segredo"
	

}

###

PUT  http://localhost:8080/usuarios
Content-Type:  application/json

{

	"id" :4 ,
    "nome":"Isabelle",
    "senha":"segredo"
	

}

###


