version: '3'

volumes:
 dados:

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    tty: true
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: safisa
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306